.PHONY: fib sshell sigblock clean

fib:
	gcc fib.c -o fib
sshell:
	gcc sshell.c -o simple_shell
sigblock:
	gcc shell.c -o shell
	gcc child.c -o child
clean:
	rm fib
	rm simple_shell
	rm shell
	rm child
